import Link from 'next/link';
import { builds, labs } from '@/lib/projects';
import { BuildCore } from '@/components/build-core';
import { MobileNav } from '@/components/mobile-nav';
import { EventLink } from '@/components/event-link';

const logoSrc = '/assets/logo.svg';

function Logo({ href = '/' }: { href?: string }) {
  return <Link className="brandLogo" href={href} aria-label="Hariom Builds home"><img src={logoSrc} alt="Hariom Builds" width={150} height={72} /></Link>;
}

export default function Home() {
  return <main>
    <nav className="nav"><Logo href="#top" /><div className="links"><EventLink href="/builds" event="build_view">Builds</EventLink><Link href="#solutions">Solutions</Link><Link href="/lab">Lab</Link><Link href="/about">About</Link><EventLink className="navCta" href="/start-a-project" event="cta_click">Start a Project</EventLink></div><MobileNav /></nav>
    <section id="top" className="hero shell"><div className="eyebrow">INDEPENDENT SOFTWARE-BUILDING STUDIO</div><div className="heroGrid"><div><h1>Digital systems built around <i>real business problems.</i></h1><p className="lead">Websites, automation, internal tools and practical AI experiences designed to make small businesses easier to run and easier to grow.</p><div className="actions"><EventLink className="button primary" href="/start-a-project" event="cta_click">Start a Project <span>↗</span></EventLink><EventLink className="button secondary" href="/builds" event="build_view">Explore Builds</EventLink></div><div className="capabilities"><span>Web</span><span>Automation</span><span>Systems</span><span>AI</span></div></div><BuildCore /></div></section>
    <section id="builds" className="section shell"><div className="sectionHead"><div><div className="eyebrow">SELECTED BUILDS</div><h2>Useful software, not just pretty screens.</h2></div><EventLink className="index" href="/builds" event="build_view">VIEW ALL →</EventLink></div><div className="cards">{builds.map((p,i)=><EventLink className="card" href={`/builds/${p.slug}`} event="build_view" key={p.slug}><div className="preview"><span className="previewNumber">0{i+1}</span><div className="previewTitle">{p.name}</div><div className="previewStatus">{p.status}</div><div className="previewLines"/></div><div className="cardMeta"><span className="status">{p.status}</span><span>BUILD / 0{i+1}</span></div><h3>{p.name}</h3><p>{p.summary}</p><span className="textLink">View case study →</span></EventLink>)}</div></section>
    <section id="solutions" className="section darkSection"><div className="shell"><div className="eyebrow">BUSINESS PROBLEMS WE SOLVE</div><h2>From scattered work to <i>working systems.</i></h2><div className="problemGrid"><div><b>01</b><h3>Getting found</h3><p>High-clarity websites that turn attention into enquiries.</p></div><div><b>02</b><h3>Repetitive work</h3><p>Automations that remove manual steps and busywork.</p></div><div><b>03</b><h3>Disconnected tools</h3><p>Internal systems that put important work in one place.</p></div><div><b>04</b><h3>AI opportunities</h3><p>Practical AI features built around a real workflow.</p></div></div></div></section>
    <section className="section shell"><div className="sectionHead"><div><div className="eyebrow">HOW WE BUILD</div><h2>Start with the problem. Ship the useful part.</h2></div></div><div className="processGrid"><div><b>01</b><h3>Understand</h3><p>Clarify the workflow, user and business constraint.</p></div><div><b>02</b><h3>Design</h3><p>Turn the problem into a focused system and clear experience.</p></div><div><b>03</b><h3>Build</h3><p>Ship the smallest useful version without unnecessary complexity.</p></div><div><b>04</b><h3>Improve</h3><p>Use feedback and evidence to decide what comes next.</p></div></div></section>
    <section id="lab" className="section shell"><div className="sectionHead"><div><div className="eyebrow">THE LAB</div><h2>Experiments before they become products.</h2></div><EventLink className="index" href="/lab" event="build_view">VIEW LAB →</EventLink></div><div className="labList">{labs.map((p,i)=><EventLink className="labItem" href={`/lab/${p.slug}`} event="build_view" key={p.slug}><span className="labNum">0{i+1}</span><strong>{p.name}</strong><span className="labStatus">{p.status}</span><span>↗</span></EventLink>)}</div></section>
    <section id="about" className="section about shell"><div><div className="eyebrow">WHY HARIOM BUILDS</div><h2>Small studio. Direct thinking. <i>Real builds.</i></h2></div><div className="aboutCopy"><p>Hariom Builds is an independent software-building studio focused on practical digital systems for service businesses, founders and small teams.</p><p>We keep the process close: understand the problem, build the smallest useful system, test it, then improve what matters.</p><Link className="textLink" href="/about">More about the studio →</Link></div></section>
    <section className="cta shell"><div className="eyebrow">START A PROJECT</div><h2>Have a business problem worth building around?</h2><p>Tell us what is slowing you down. We’ll turn the conversation into a clear next step.</p><EventLink className="button primary" href="/start-a-project" event="cta_click">Start a Project <span>↗</span></EventLink><small>Reply within 24–48 hours.</small></section>
    <footer className="footer shell"><Logo /><p>Independent software-building studio.</p><div><Link href="/about">About</Link><Link href="/start-a-project">Contact</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></footer>
  </main>;
}
