'use client';

export function PremiumUpgrades() {
  return <style jsx global>{`
    .heroFloat{position:absolute;right:2%;bottom:92px;width:178px;padding:13px 15px;border:1px solid #39432f;background:#0b0e0ad9;backdrop-filter:blur(14px);box-shadow:0 18px 50px #0008;border-radius:12px;display:grid;gap:5px;animation:floatBadge 4s ease-in-out infinite;z-index:5}.heroFloat span,.heroFloat small{font:8px monospace;letter-spacing:.12em;color:#697265}.heroFloat strong{font-size:13px;letter-spacing:.05em}.heroFloat strong i{font-style:normal;color:#b7ff3c;text-shadow:0 0 10px #b7ff3c}.heroFloat:before{content:"";position:absolute;left:-1px;top:12px;width:2px;height:25px;background:#b7ff3c;box-shadow:0 0 14px #b7ff3c}

    .caseMini{margin-top:18px;padding:13px 14px;border:1px solid #272d25;background:#0a0c09;display:grid;gap:7px;border-radius:8px}.caseMini span{font:8px monospace;letter-spacing:.14em;color:#6d7567}.caseMini b{font-size:11px;line-height:1.45;font-weight:500;color:#aeb4a9}

    .stackStrip{overflow:hidden;border-top:1px solid #232820;border-bottom:1px solid #232820;background:#0a0c09;white-space:nowrap}.stackTrack{display:flex;width:max-content;animation:stackMarquee 28s linear infinite}.stackTrack span{display:inline-flex;align-items:center;gap:28px;padding:18px 28px;font:10px monospace;letter-spacing:.14em;color:#747c70}.stackTrack b{color:#b7ff3c;font-size:11px}

    .servicesSection{background:#0b0d0a;border-top:1px solid #20251e;border-bottom:1px solid #20251e}.servicesIntro{display:flex;justify-content:space-between;gap:40px;align-items:end}.servicesIntro p{max-width:420px;color:#858c81;line-height:1.6;margin:0}.serviceGrid{display:grid;grid-template-columns:repeat(4,1fr);margin-top:55px;border-top:1px solid #2c3329;border-left:1px solid #2c3329}.serviceCard{min-height:330px;padding:25px;border-right:1px solid #2c3329;border-bottom:1px solid #2c3329;position:relative;overflow:hidden;transition:transform .4s cubic-bezier(.2,.8,.2,1),background .35s ease,border-color .35s ease}.serviceCard:before{content:"";position:absolute;width:220px;height:220px;border-radius:50%;right:-110px;top:-110px;background:#b7ff3c0d;transition:transform .5s ease}.serviceCard:hover{transform:translateY(-8px);background:#10140e;border-color:#4b593e}.serviceCard:hover:before{transform:scale(1.6)}.serviceTop{display:flex;justify-content:space-between;align-items:center}.serviceTop span{font:11px monospace;color:#b7ff3c}.serviceTop small{font:8px monospace;color:#596154}.serviceCard h3{font-size:25px;letter-spacing:-.04em;margin:75px 0 12px;max-width:220px}.serviceCard p{color:#7f877b;line-height:1.55;font-size:13px;max-width:260px}.serviceArrow{position:absolute;right:22px;bottom:18px;color:#b7ff3c;font:18px monospace;transition:transform .3s ease}.serviceCard:hover .serviceArrow{transform:translate(4px,-4px)}

    .proofSection{padding-top:30px}.proofPanel{display:grid;grid-template-columns:1fr .9fr;gap:70px;padding:60px;border:1px solid #30382b;background:radial-gradient(circle at 0 0,#182017,#0b0e0a 48%);position:relative;overflow:hidden}.proofPanel:after{content:"";position:absolute;width:320px;height:320px;right:-170px;bottom:-190px;border-radius:50%;border:1px solid #b7ff3c22;box-shadow:0 0 70px #b7ff3c0c}.proofPanel p{max-width:650px;color:#858c82;line-height:1.7}.proofGrid{border-top:1px solid #394231}.proofGrid div{display:grid;grid-template-columns:35px 1fr auto;gap:10px;align-items:center;padding:16px 0;border-bottom:1px solid #394231}.proofGrid strong,.proofGrid span{font:9px monospace;color:#687063}.proofGrid b{font-size:11px;letter-spacing:.1em}.proofGrid span{text-align:right}

    .faqSection{padding-top:80px}.faqGrid{display:grid;grid-template-columns:1fr 1fr;gap:0 55px;margin-top:50px;border-top:1px solid #2b3029}.faqGrid details{border-bottom:1px solid #2b3029;padding:20px 0}.faqGrid summary{cursor:pointer;list-style:none;font-size:17px;font-weight:700;display:flex;justify-content:space-between;gap:20px}.faqGrid summary::-webkit-details-marker{display:none}.faqGrid summary:after{content:'+';color:#b7ff3c;font:18px monospace}.faqGrid details[open] summary:after{content:'−'}.faqGrid p{color:#7f877b;line-height:1.6;max-width:500px;margin:14px 0 2px;font-size:13px}

    @keyframes stackMarquee{from{transform:translateX(0)}to{transform:translateX(-50%)}}@keyframes floatBadge{0%,100%{transform:translateY(0) rotate(.5deg)}50%{transform:translateY(-8px) rotate(-.5deg)}}

    @media(max-width:900px){.heroFloat{right:0;bottom:80px}.serviceGrid{grid-template-columns:1fr 1fr}.servicesIntro,.proofPanel{grid-template-columns:1fr;display:grid}.proofPanel{gap:35px}.faqGrid{grid-template-columns:1fr}.heroFloat{display:none}}
    @media(max-width:760px){.hero{padding-top:65px}.heroGrid{grid-template-columns:1fr}.stackTrack{animation-duration:22s}.serviceGrid{grid-template-columns:1fr}.serviceCard{min-height:270px}.serviceCard h3{margin-top:55px}.proofPanel{padding:30px 22px}.faqGrid{margin-top:35px}.caseMini{display:none}.stackStrip{margin-top:0}.heroTrust{flex-direction:column;gap:8px}.scrollCue{display:none}}
    @media(prefers-reduced-motion:reduce){.stackTrack,.heroFloat{animation:none!important}.serviceCard:hover{transform:none}}
  `}</style>;
}
